spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/employees_db
    username: myuser
    password: mypass
    driver-class-name: com.mysql.cj.jdbc.Driver
  show-sql: true
resilience4j:
  circuitbreaker:
    instances:
      departmentService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      departmentService:
        maxAttempts: 3
        waitDuration: 2s

employee:
  cache-enabled: true
